### PR TITLE
Add a preface to the spells chapter

### PR DESCRIPTION
**Pull request by BenOvermyer**
This adds a description of the spell format to the spells chapter, and corrects a couple minor typos.

## Motivation

This clarifies the formatting of spells.

## Changes
- Add preface to spells chapter
- Remove trailing `.` character on some ranges
-

@ElectricCoffee

### CODE REVIEW

**Comment by ElectricCoffee** [comment]
Loving the change, I'm pulling it immediately!

**Comment by ElectricCoffee** [comment]
I should probably make this an official rule, but please make these requests pull into develop. For some reason I couldn't change the target branch myself

**Comment by BenOvermyer** [comment]
> I should probably make this an official rule, but please make these requests pull into develop. For some reason I couldn't change the target branch myself

Oof, sorry about that.

**Comment by ElectricCoffee** [comment]
it's fine, it just messes up the version numbers, as I now have to bump the one on master, rather than putting it all into the develop branch for the next release

**Comment by BenOvermyer** [comment]
Maybe with that bump, you could also call that out in the CONTRIBUTING.md guide for clarity.

**Comment by ElectricCoffee** [comment]
good call!

**Comment by BenOvermyer** [comment]
BTW, I also write manuscripts for RPGs in LaTeX, and my wife and I are planning to move to Estonia in a couple years. Thought that was a fun coincidence!

**Comment by ElectricCoffee** [comment]
That is a fun coincidence!

I'm curious: how did you find out about Siren?

**Comment by BenOvermyer** [comment]
I found it by exploring GitHub's `tabletop-rpgs` topic, and this had some of the most stars of the topic.

**Comment by ElectricCoffee** [comment]
I'll add you to the contributor section at the very least! thank you so much!

**Comment by BenOvermyer** [comment]
Thanks! I plan on having a deeper read of the manuscript this weekend.

**Comment by ElectricCoffee** [comment]
go ahead!

I'm also working on a side-project, a module for this called Curse of Transience.

It's a Science-Fantasy type setting that turns some of the conventional rules on their head.

It's gonna take years before it's even remotely ready to be presented to the public though.

**Comment by BenOvermyer** [comment]
That sounds intriguing. I look forward to seeing it.

**Pull request merged**
